name: flutter_readium_example
description: Demonstrates how to use the flutter_readium plugin.

version: 0.0.0+0

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.27.1'

dependencies:
  flutter:
    sdk: flutter

  archive:
  audio_service:
    git:
      url: https://github.com/Notalib/audio_service.git
      ref: lyt
      path: audio_service
  cupertino_icons: ^1.0.2
  file_picker:
  flutter_bloc:
  flutter_readium:
    path: ../
  native_device_orientation:
  path:
  path_provider:
  pointer_interceptor: ^0.10.1+2
  xml:

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint:

flutter:
  uses-material-design: true
  assets:
    - assets/pubs/
    - assets/opdsList.json
