name: flutter_readium_platform_interface
description: A common platform interface for the flutter_readium plugin.
version: 0.0.1
homepage: https://github.com/notalib/flutter_readium
repository: https://github.com/notalib/flutter_readium
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.8.0
  freezed_annotation:
  json_annotation: ^4.9.0
  json_diff:
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=4.0.0 <6.0.0"

  build_runner:
  freezed:
  json_serializable:
